#!/bin/sh
#
# ufetch-manjaro - tiny system info for manjaro

## INFO

# user is already defined
host="$(hostname)"
os='Manjaro'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename "$SHELL")"
terminal="$TERM"

## UI DETECTION

ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
ui_type='WM'

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	green_bg="$(tput setab 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
bold_green_fg="${reset}${bold}${green}" # bold, green, foreground
bold_white_fg="${reset}${bold}${white}" # bold, white, foreground
## OUTPUT

cat <<EOF

${bold_green_fg}  ███████${bold_white_fg}╗${bold_green_fg}███████${bold_white_fg}╗        [${bold_green_fg}OS${bold_white_fg}]  ${os}${reset}
${bold_green_fg}  ██${bold_white_fg}╔════╝${bold_green_fg}██${bold_white_fg}╔════╝    [${bold_green_fg}KERNEL${bold_white_fg}]  ${kernel}${reset}
${bold_green_fg}  █████${bold_white_fg}╗  ${bold_green_fg}█████${bold_white_fg}╗      [${bold_green_fg}UPTIME${bold_white_fg}]  ${uptime}${reset}
${bold_green_fg}  ██${bold_white_fg}╔══╝  ${bold_green_fg}██${bold_white_fg}╔══╝    [${bold_green_fg}PACKAGES${bold_white_fg}]  ${packages}${reset}
${bold_green_fg}  ██${bold_white_fg}║     ${bold_green_fg}██${bold_white_fg}║          [${bold_green_fg}SHELL${bold_white_fg}]  ${shell}${reset}
${bold_white_fg}  ╚═╝     ╚═╝             [${bold_green_fg}${ui_type}${bold_white_fg}]  ${ui}${reset}
${bold_green_fg}  ${USER}${bold_white_fg}@${bold_green_fg}${host}       ${bold_white_fg}[${bold_green_fg}TERMINAL${bold_white_fg}]  ${terminal}${reset}

EOF
