#!/bin/sh
#
# ufetch-manjaro - tiny system info for manjaro

## INFO

# user is already defined
host="$(hostname)"
os='Manjaro'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename "$SHELL")"
terminal="$TERM"

## UI DETECTION

ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
uitype='WM'

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
gc="${reset}${bold}${green}"        # green color
wc="${reset}${bold}${white}"        # white color

## OUTPUT

cat <<EOF

${gc}  ███████${wc}╗${gc}███████${wc}╗${wc}        [${gc}OS${wc}]  ${os}${reset}
${gc}  ██${wc}╔════╝${gc}██${wc}╔════╝${wc}    [${gc}KERNEL${wc}]  ${kernel}${reset}
${gc}  █████${wc}╗  ${gc}█████${wc}╗  ${wc}    [${gc}UPTIME${wc}]  ${uptime}${reset}
${gc}  ██${wc}╔══╝  ${gc}██${wc}╔══╝  ${wc}  [${gc}PACKAGES${wc}]  ${packages}${reset}
${gc}  ██${wc}║     ${gc}██${wc}║     ${wc}     [${gc}SHELL${wc}]  ${shell}${reset}
${wc}  ╚═╝     ╚═╝             [${gc}${uitype}${wc}]  ${ui}${reset}
${gc}  ${USER}${wc}@${gc}${host}${reset} ${wc}      [${gc}TERMINAL${wc}]  ${terminal}${reset}

EOF
