#!/usr/bin/sh

# Description: Navigate to directory using z
#
# Requires: z - https://github.com/rupa/z
#
# Note: z [-chlrtx] [regex1 regex2 ... regexn]
#
# Shell: POSIX compliant
# Author: Volkan Erdogan

if [ -f "$ZSH/plugins/z/z.sh" ]; then
  printf "jump to: "
  read -r dir
  odir="$(z "$dir")"
  printf "%s" "0$odir" > "$NNN_PIPE"
else
  printf "z missing"
  read -r _
fi
