#!/usr/bin/env bash
#
# Checks status of dropbox
#
# Usage: dropbox-status
#
#   $ dropbox-status

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

status=$(echo -n $(dropbox-cli status) | awk END{print})

if [[ ${status} == "Dropbox isn't running!" ]]; then
    echo "%{F#ff5555} down" # daemon down
elif [[ ${status} == "Dropbox isn't responding!" ]]; then
    echo "%{F#f1fa8c} dead" # something went wrong
elif [[ ${status} == Sync* ]]; then
    echo "%{F#0189cc} snycing" # syncing & indexing files
else
    echo "%{F#50fa7b} in sync" # up to date
fi
 
exit $?
