#!/usr/bin/env bash
#
# Quickly enable/disable git url rewrite configuration
#
# Usage: git-url-rewrite [-e|-d] [-h]
#
#   $git-url-rewrite [-e|-d] [-h]
#

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

option="${1:-}"
flag=false

usage() {
  echo "Usage: $0 [OPTIONS]"
  echo -e "\nLONG VIEW OPTIONS"
  echo -e "   -h, \tDisplay this help message"
  echo -e "   -e, \tEnable url rewrite"
  echo -e "   -d, \tDisable url rewrite"
  echo -e "\nEnable/disable usage of git@github.com[:] instead of git://github.com and https://github.com."
}

if [[ -z ${option} ]]; then
  usage
  exit 0
else
  while getopts ':edh-:' opt; do
    if [ "${opt}" = "-" ]; then
      opt="${OPTARG%%=*}"
    fi
    case $opt in
      e)
        if [ ${flag} = false ]; then
          git config --global url.git@github.com.insteadOf git://github.com
          git config --global url.git@github.com:.insteadOf https://github.com
          flag=true
        fi
        ;;
      d)
        if [ ${flag} = false ]; then
          git config --global --unset url.git@github.com.insteadOf
          git config --global --unset url.git@github.com:.insteadOf
          flag=true
        fi
        ;;
      h)
        usage
        exit 0
        ;;
      *)
        echo "Invalid option: -$opt" >&2
        echo -e "\r"
        usage
        exit 1
        ;;
    esac
  done
fi

exit $?
