#!/usr/bin/env bash
#
# Quickly enable/disable git url rewrite configuration
#
# Usage: git-url-rewrite [-e|-d] [-h]
#
#   $git-url-rewrite [-e|-d] [-h]
#

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

options="${1:-}"
flag=false

usage() {
  echo "Usage: git-url-rewrite [OPTIONS]"
  echo -e "\nLONG VIEW OPTIONS"
  echo -e "   -h, --help\t\tDisplay this help message"
  echo -e "   -e, --enable\t\tEnable url rewrite"
  echo -e "   -d, --disable\tDisable url rewrite"
  echo -e "\nEnable/disable usage of git@github.com[:] instead of git://github.com and https://github.com."
}

if [[ -z ${options} ]]; then
  usage
  exit 0
else
  while getopts ':edh-:' opt; do
    if [ "${opt}" = "-" ]; then
      opt="${OPTARG%%=*}"
    fi
    case $opt in
      e | enable)
        if [ ${flag} = false ]; then
          git config --global url.git@github.com.insteadOf git://github.com
          git config --global url.git@github.com:.insteadOf https://github.com
          flag=true
        fi
        ;;
      d | disable)
        if [ ${flag} = false ]; then
          git config --global --unset url.git@github.com.insteadOf
          git config --global --unset url.git@github.com:.insteadOf
          flag=true
        fi
        ;;
      h | help)
        usage
        exit 0
        ;;
      *)
        echo "Invalid option: -$OPTARG" >&2
        echo -e "\r"
        usage
        exit 2
        ;;
    esac
  done
fi

exit $?
