#!/usr/bin/env bash
#
# Converts a given JPG image to given quality and resizes it without overriding the original file. Default quality value is 70.
#
# Usage: img-convert FILENAME [QUALITY]
#
#   $ img-convert foo 70

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

filename="${1:?Usage: img-convert FILENAME [QUALITY]}"
num_quality="${2:-70}"

convert ${filename}.jpg -quality ${num_quality} low_${filename}.jpg
convert ${filename}.jpg -quality ${num_quality} low_${filename}.webp
convert ${filename}.jpg -quality ${num_quality} -resize 50% "${filename}"_"${num_quality}"q_50pc.jpg
convert ${filename}.jpg -quality ${num_quality} -resize 50% "${filename}"_"${num_quality}"q_50pc.webp

exit $?
