#!/bin/bash
# Launch Polybar, using default config location ~/.config/polybar/config

# Terminate already running bar instances
killall -q -s SIGKILL polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if hash polybar >/dev/null 2>&1; then
  MONITOR=$(xrandr -q | grep -e "(\sconnected)(\sprimary)*" | cut -d" " -f1) polybar -r alienware &
fi
