#!/usr/bin/env bash
#
# Opens fzf with a file preview
#
# Usage: preview PATTERN
#
#   $ preview PATTERN

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

pattern="${1:-}"

if [[ -z ${pattern} ]]; then
  echo "error: The following required arguments were not provided:"
  echo "    <PATTERN>"
  echo -e "\nUsage:\n";
  echo "    preview PATTERN";
else
  rg --files-with-matches --no-messages "$1" | fzf --preview "bat --color always {} 2>/dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}" 
fi

exit $?
