#!/usr/bin/env bash
#
# Opens fzf with a file preview
#
# Usage: preview PATTERN [PATH]
#
#   $ preview PATTERN [PATH]

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

pattern="${1:-}"
path="${2:-.}"

if [[ -z ${pattern} ]]; then
  echo "error: The following required arguments were not provided:"
  echo "    <PATTERN>"
  echo -e "\nUsage:\r";
  echo "    preview PATTERN";
else
  rg --files-with-matches --no-messages --hidden --glob "!.git" --ignore-case "${pattern}" "${path}" | fzf --preview "bat --color always {} 2>/dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '${pattern}' || rg --ignore-case --pretty --context 10 '${pattern}' {}"
fi

exit $?
