#!/usr/bin/env bash
#
# Set wallpaper(s) according to number of monitors.
# Default directory for wallpapers is ~/.dotfiles/wallpapers.
#
# Usage: set-random-wallpaper [DIRECTORY]
#
#   $ set-random-wallpaper ~/Pictures/Wallpapers

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

dir_wallpaper="${1:-${HOME}/.dotfiles/wallpapers}"

if hash feh >/dev/null 2>&1; then
  feh --no-fehbg --bg-max --randomize "${dir_wallpaper}"
fi

exit $?
