#!/usr/bin/env bash
#
# Set up monitors. Maximum three monitors can be connected.
#
# Usage: triple-monitor-setup [OPTIONS]
#
#   $ triple-monitor-setup
#
# Create a udev rule to automatically change the monitor setup on connect/disconnect event (https://wiki.archlinux.org/index.php/Udev)
# /etc/udev/rules.d/99-monitor-changed.rules
# ACTION=="change", SUBSYSTEM="drm", RUN+="/path/to/triple-monitor-setup"

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Workaround to turn on connected outputs that may be in suspend mode and hence shown as disconnected
init() {
  local -i count=1
  local -i seconds=1
  while((count)); do
      xrandr &> /dev/null
      sleep $seconds
      ((count--))
  done
}

setup_monitors() {
  card_id=0

  if [[ -s /sys/class/drm/card1-LVDS-1/status ]]; then
    card_id=1
  fi

  dmode_hdmi1="$(cat /sys/class/drm/card${card_id}-HDMI-A-1/status)"
  dmode_vga1="$(cat /sys/class/drm/card${card_id}-VGA-1/status)"

  output_lvds1="--output LVDS1 --primary --mode 1600x900 --rotate normal --pos 0x0" # laptop screen, is always on
  output_hdmi1="--output HDMI1 --off" # LEFT screen
  output_vga1="--output VGA1 --off" # RIGHT screen

  # turn off
  # xrandr --output DVI-D-1-1 --off --output VIRTUAL1 --off --output DP2 --off --output DP1 --off --output eDP-1-1 --off --output HDMI2 --off ${output_hdmi1} ${output_lvds1} ${output_vga1} &> /dev/null

  if [[ ${dmode_hdmi1} = "connected" ]]; then
    output_hdmi1="--output HDMI1 --crtc 1 --mode 1920x1080 --rotate normal --pos 0x0"
    output_lvds1="--output LVDS1 --primary --mode 1600x900 --rotate normal --pos 1920x0"
  fi

  if [[ ${dmode_vga1} == "connected" ]]; then
    output_lvds1="--output LVDS1 --primary --mode 1600x900 --rotate normal --pos 0x0"
    output_vga1="--output VGA1 --crtc 2 --mode 1920x1080 --rotate normal --pos 1600x0"
    if [[ ${dmode_hdmi1} = "connected" ]]; then
      output_lvds1="--output LVDS1 --primary --mode 1600x900 --rotate normal --pos 1920x0"
      output_vga1="--output VGA1 --crtc 2 --mode 1920x1080 --rotate normal --pos 3520x0"
    fi
  fi

  # turn on
  xrandr --output DVI-D-1-1 --off --output VIRTUAL1 --off --output DP2 --off --output DP1 --off --output eDP-1-1 --off --output HDMI2 --off $output_hdmi1 $output_lvds1 $output_vga1 &> /dev/null
}

init
setup_monitors

while getopts ':pw' opt; do
  case ${opt} in
    p)
      launch-polybar &>/dev/null
      ;;
    w)
      set-random-wallpaper &>/dev/null
      ;;
    *)
      ;;
  esac
done

exit $?
