#!/bin/sh
#
# ufetch-manjaro - tiny system info for manjaro

## INFO

# user is already defined
os="$(cat /etc/os-release | grep 'PRETTY' | cut -d '=' -f 2 | sed 's/"//g')"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"

## UI DETECTION

ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
ui_type='WM'

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	green="$(tput setaf 2)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
  # you can change these
  bold_green_fg="${reset}${bold}${green}" # bold, green, foreground
  bold_white_fg="${reset}${bold}${white}" # bold, white, foreground
fi

## OUTPUT
cat <<EOF

${bold_green_fg}       █████${bold_white_fg}══╗         [${bold_green_fg}USER${bold_white_fg}]  ${bold_green_fg}${USER}
${bold_green_fg}     █████████${bold_white_fg}╚═╗       [${bold_green_fg}HOST${bold_white_fg}]  ${bold_green_fg}$(hostname)
${bold_green_fg}   █████████████${bold_white_fg}║         [${bold_green_fg}OS${bold_white_fg}]  ${os}
${bold_green_fg}   ██${bold_white_fg}╔═╗${bold_green_fg}███${bold_white_fg}╔═╗${bold_green_fg}██${bold_white_fg}║     [${bold_green_fg}KERNEL${bold_white_fg}]  ${kernel}
${bold_green_fg}   █████████████${bold_white_fg}║     [${bold_green_fg}UPTIME${bold_white_fg}]  ${uptime}
${bold_green_fg}     ████ ████${bold_white_fg}╔═╝   [${bold_green_fg}PACKAGES${bold_white_fg}]  ${packages}
${bold_green_fg}       █████${bold_white_fg}╔═╝        [${bold_green_fg}SHELL${bold_white_fg}]  $(basename "$SHELL")
${bold_green_fg}       █${bold_white_fg}║${bold_green_fg}█${bold_white_fg}║${bold_green_fg}█${bold_white_fg}║             [${bold_green_fg}${ui_type}${bold_white_fg}]  ${ui}
${bold_green_fg}       █${bold_white_fg}║${bold_green_fg}█${bold_white_fg}║${bold_green_fg}█${bold_white_fg}║       [${bold_green_fg}TERMINAL${bold_white_fg}]  ${TERM}
${bold_white_fg}       ╚╝╚╝╚╝${reset}

EOF
