#!/usr/bin/env bash
#
# Checks status of wireguard
#
# Usage: wg-status INTERFACE
#
#   $ wg-status wireguard1

# This option will make the script exit when there is an error
set -o errexit
# This option will make the script exit when last command threw an error
set -o pipefail
# This option will make the script exit when it tries to use an unset variable
set -o nounset
# Trace what gets executed
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

interface="${1:?Unknown interface}"

status=$(echo -n $(ip addr show dev ${interface} 2>/dev/null | awk 'END { print NR }'))

if [[ ${status} == "0" ]]; then
    echo -n "%{F#ff5555} off"
elif [[ -n ${status} ]]; then
    echo -n "%{F#50fa7b} on"
fi
 
exit $?
