#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = 'dracula'
  colorscheme_bg = 'dark'
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = 'arrow'
  statusline_inactive_separator = 'arrow'
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  # font
  guifont = 'Hack:h11'
  # set file manager
  filemanager = 'nerdtree'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = 'complete'
  auto-completion-tab-key-behavior = 'smart'

# Enable git layer
[[layers]]
  name = 'git'

# Enable language layers
[[layers]]
  name = 'lang#asciidoc'
[[layers]]
  name = 'lang#extra'
[[layers]]
  name = 'lang#elm'
[[layers]]
  name = 'lang#html'
[[layers]]
  name = 'lang#javascript'
[[layers]]
  name = 'lang#markdown'
[[layers]]
  name = 'lang#php'
[[layers]]
  name = 'lang#python'
  format_on_save = 1
[[layers]]
  name = 'lang#sh'
[[layers]]
  name = 'lang#typescript'
[[layers]]
  name = 'lang#vim'

# Enable lsp layer
[[layers]]
  name = 'lsp'
  filetypes = [
    'css',
    'elm',
    'html',
    'javascript',
    'php',
    'python',
    'sh',
    'typescript'
  ]
  [layers.override_cmd]
    typescript = ['tsserver']
    elm = ['elm-language-server']
    php = ['/home/fred/.config/composer/vendor/felixfbecker/language-server/bin/php-language-server.php']


# Enable shell layer
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

# Enable tools layer
[[layers]]
  name = 'tools'

# Enable unite layer
[[layers]]
  name = 'unite'

# Custom plugins
[[custom_plugins]]
  name = 'dracula/vim'
  merged = false
