(setq php-backend 'lsp)
(add-to-list 'auto-mode-alist '("\\.blade.php\\'" . web-mode))
(setq php-mode-coding-style 'psr2)
(setq php-mode-enable-psr2-coding-style t)
(setq php-mode-enable-project-coding-style t)
