#!/bin/bash
# Launch Polybar, using default config location ~/.config/polybar/config

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

MONITOR=$(xrandr -q | grep " connected primary" | cut -d" " -f1) polybar -r alienware &
